---
stages:
  - build
  - test

build:
  stage: build
  image: node:20.16.0-alpine3.20
  script:
      - yarn install --frozen-lockfile
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/

lint:
  stage: test
  image: node:20.16.0-alpine3.20
  script:
    - yarn install --frozen-lockfile
    - yarn lint

test:
  stage: test
  image: node:20.16.0-alpine3.20
  script:
    - yarn install --frozen-lockfile
    - yarn test
...
