---
stages:
  - build
  - test

default:
  tags:
    - general
  cache: &yarn_cache
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull-push



build:
  stage: build
  image: node:20.16.0-alpine3.20
  script:
      - yarn install --frozen-lockfile

lint:
  stage: test
  image: node:20.16.0-alpine3.20
  script:
    - yarn lint-ci
  cache:
    <<: *yarn_cache
    policy: pull
  artifacts:
    when: always
    paths:
      - junit.xml
    reports:
      junit: junit.xml

test:
  stage: test
  image: node:20.16.0-alpine3.20
  script:
    - yarn test
  cache:
    <<: *yarn_cache
    policy: pull
...
