---
stages:
  - build
  - test

default:
  tags:
    - general

cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules/

build:
  stage: build
  image: node:20.16.0-alpine3.20
  script:
      - yarn install --frozen-lockfile

lint:
  stage: test
  image: node:20.16.0-alpine3.20
  script:
    - yarn lint

test:
  stage: test
  image: node:20.16.0-alpine3.20
  script:
    - yarn test
...
